#!/bin/bash
#pull commits from develop and create a new branch

#get branch name and stop execution if it was not provided
branch=$1
if [ $# -eq 0 ]; then
    echo "Please provide a name to the branch, as in:"
    echo "./git-branch branchname"
    exit 1
fi

echo "Pulling from branch docker_vr:"
git checkout docker_vr
git pull

echo "Creating branch..."
git checkout -b $1 
git branch