#!/bin/bash
#push changes to current branch
set -e

#get commit message stop execution if it was not provided
msg=$1
if [ $# -eq 0 ]; then
    echo "Please provide a commit message, as in:"
    echo "./git-push 'sample message'"
    exit 1
fi

#prepare to push
echo "Comitting..."
git add -A
git commit -m "$msg"

#get current branch and push to it
echo "Pushing..."
branch=$(git rev-parse --abbrev-ref HEAD)
git push origin $branch
