#!/bin/bash
# Initialize sample

set -e

ROOT_FOLDER=$(pwd)
GREEN='\033[0;32m'
CLEAR='\033[0m'

sample_model(){
echo -e "Which model would you like to use?
[${GREEN}1${CLEAR}] ${GREEN}DVID${CLEAR} (Delegated Assertions)
[${GREEN}2${CLEAR}] ${GREEN}ID Mode${CLEAR} (Nested Tokens)
[${GREEN}3${CLEAR}] ${GREEN}Anonymous Mode${CLEAR} (Nested Tokens)
[${GREEN}4${CLEAR}] ${GREEN}LSVID${CLEAR} (Lightweight SVID)"
read input
case "$input" in
  [1])
    MODEL_PATH=$ROOT_FOLDER/samples/SVID-NG
  ;;
  [2])
    MODEL_PATH=$ROOT_FOLDER/samples/IDMode  
  ;;
  [3])
    MODEL_PATH=$ROOT_FOLDER/samples/anonymousMode  
  ;;
  [4])
    MODEL_PATH=$ROOT_FOLDER/samples/phase3  
  ;;
  *)
    echo "Invalid input".
    sample_model
  ;;
esac
}
sample_model


echo -e "${GREEN}Killing spire agent/server${CLEAR}\n"
cd $MODEL_PATH
$ROOT_FOLDER/scripts/kill_lsvid_spire.sh
echo -e "${GREEN}Starting SPIRE...${CLEAR}\n"
cd /opt/spire-signed-assertions
##  Start SPIRE Agent and Server
sudo bash start_spire_env.sh > /dev/null

echo -e "${GREEN}Applying .cfg ...${CLEAR}\n"
cd $MODEL_PATH
cp $ROOT_FOLDER/conf/.cfg Assertingwl-mTLS
cp $ROOT_FOLDER/conf/.cfg m-tier
[ -d "m-tier2" ] && cp $ROOT_FOLDER/conf/.cfg m-tier2 #not all models have this WL
[ -d "m-tier3" ] && cp $ROOT_FOLDER/conf/.cfg m-tier3
[ -d "m-tier4" ] && cp $ROOT_FOLDER/conf/.cfg m-tier4
[ -d "m-tier5" ] && cp $ROOT_FOLDER/conf/.cfg m-tier5
cp $ROOT_FOLDER/conf/.cfg subject_workload
cp $ROOT_FOLDER/conf/.cfg target-wl

echo -e "${GREEN}Starting containers...${CLEAR}\n"
docker-compose up --build --detach

#TODO (optimization): Make Anon and ID modes accept binaries
if [ "$input" == "1" ]; then
  echo -e "${GREEN}Copying WLs' binaries from containers to host..${CLEAR}\n"

  rm -f ./Assertingwl-mTLS/bin/*
  docker cp svid-ng_assertingwl_1:/build/bin/. ./Assertingwl-mTLS/bin/
  rm -f ./m-tier/bin/*
  docker cp svid-ng_m-tier_1:/build/bin/. ./m-tier/bin/
  rm -f ./subject_workload/bin/*
  docker cp svid-ng_subjectwl_1:/build/bin/. ./subject_workload/bin/
  rm -f ./target-wl/bin/*
  docker cp svid-ng_target-wl_1:/build/bin/. ./target-wl/bin/
elif [ "$input" == "4" ]; then
  echo -e "${GREEN}Copying WLs' binaries from containers to host..${CLEAR}\n"

  rm -f ./Assertingwl-mTLS/bin/*
  docker cp phase3_assertingwl_1:/build/bin/. ./Assertingwl-mTLS/bin/
  rm -f ./subject_workload/bin/*
  docker cp phase3_subjectwl_1:/build/bin/. ./subject_workload/bin/
  rm -f ./m-tier/bin/*
  docker cp phase3_m-tier_1:/build/bin/. ./m-tier/bin/
  rm -f ./target-wl/bin/*
  docker cp phase3_target-wl_1:/build/bin/. ./target-wl/bin/
fi 

echo -e "${GREEN}Done! Containers up and running.${CLEAR}"