version: "3"

services:
  common:
    build:
      context: ../..
      dockerfile: samples/SVID-NG/common/Dockerfile
    volumes:
      - /tmp/spire-agent/public/api.sock:/tmp/spire-agent/public/api.sock
    networks:
      - my-network

  assertingwl:
    build:
      context: ../..
      dockerfile: samples/SVID-NG/Assertingwl-mTLS/Dockerfile
    ports:
      - "8443:8443"
    volumes:
      - /tmp/spire-agent/public/api.sock:/tmp/spire-agent/public/api.sock
    networks:
      - my-network

  subjectwl:
    build:
      context: ../..
      dockerfile: samples/SVID-NG/subject_workload/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - /tmp/spire-agent/public/api.sock:/tmp/spire-agent/public/api.sock
    networks:
      - my-network

  m-tier:
    build:
      context: ../..
      dockerfile: samples/SVID-NG/m-tier/Dockerfile
    ports:
      - "8445:8445"
    volumes:
      - /tmp/spire-agent/public/api.sock:/tmp/spire-agent/public/api.sock
    networks:
      - my-network

  target-wl:
    build:
      context: ../..
      dockerfile: samples/SVID-NG/target-wl/Dockerfile
    ports:
      - "8444:8444"
    volumes:
      - /tmp/spire-agent/public/api.sock:/tmp/spire-agent/public/api.sock
    networks:
      - my-network

networks:
  my-network:
