#!/bin/bash
#configure the environment (according to config file), kill SPIRE and containers and init environment from zero.

SCRIPT_PATH=$(pwd)

#configure according to .cfg file
chmod +x config
./config

#kill spire agent, spire server and containers
cd /opt/spire
sudo kill -9 $(ps -ef | grep "spire-agent" | grep -v grep | awk '{print $2}') ;  sudo kill -9 $(ps -ef | grep "spire-server" | grep -v grep | awk '{print $2}') ; sudo rm -rf .data
echo "Spire Agent/Server killed"

docker rm $(docker stop $(docker ps -a -q))
echo "Containers killed"

#start spire
sudo ./start_spire_env.sh
sleep 15

#start containers
cd $SCRIPT_PATH
cd ./Assertingwl-mTLS
docker build -t asserting-wl -f Dockerfile ..
docker run --rm -i -t -p 8443:8443 -v /tmp/spire-agent/public/api.sock:/tmp/spire-agent/public/api.sock -d asserting-wl

cd ../subject_workload
docker build -t subject-wl -f Dockerfile ..
docker run --rm -i -t -p 8080:8080 -v /tmp/spire-agent/public/api.sock:/tmp/spire-agent/public/api.sock -d subject-wl

cd ../target_workload
docker build  -t target-wl -f Dockerfile ..
docker run --rm -i -t -p 8444:8444 -v /tmp/spire-agent/public/api.sock:/tmp/spire-agent/public/api.sock -d target-wl

cd ../middle-tier
docker build  -t middle-tier -f Dockerfile ..
docker run --rm -i -t -p 8445:8445 -v /tmp/spire-agent/public/api.sock:/tmp/spire-agent/public/api.sock -d middle-tier

cd ../middle-tier2
docker build -t middle-tier2 -f Dockerfile ..
docker run --rm -i -t -p 8446:8446 -v /tmp/spire-agent/public/api.sock:/tmp/spire-agent/public/api.sock -d middle-tier2

cd ../middle-tier3
docker build -t middle-tier3 -f Dockerfile ..
docker run --rm -i -t -p 8447:8447 -v /tmp/spire-agent/public/api.sock:/tmp/spire-agent/public/api.sock -d middle-tier3

cd ../middle-tier4
docker build -t middle-tier4 -f Dockerfile ..
docker run --rm -i -t -p 8448:8448 -v /tmp/spire-agent/public/api.sock:/tmp/spire-agent/public/api.sock -d middle-tier4

cd ../middle-tier5
docker build -t middle-tier5 -f Dockerfile ..
docker run --rm -i -t -p 8449:8449 -v /tmp/spire-agent/public/api.sock:/tmp/spire-agent/public/api.sock -d middle-tier5
