#!/bin/bash
# Initialize sample

set -e

SCRIPT_PATH=$(pwd)
GREEN='\033[0;32m'
CLEAR='\033[0m'

printf "${GREEN}Killing spire agent, spire server and containers...${CLEAR}\n"
./kill

printf "${GREEN}Starting SPIRE...${CLEAR}\n"
cd /opt/spire
sudo ./start_spire_env.sh > /dev/null

printf "${GREEN}Starting containers...${CLEAR}\n"
cd $SCRIPT_PATH
docker-compose up --build --detach

printf "${GREEN}Copying WLs' binaries from containers to host..${CLEAR}\n"
rm -f ./Assertingwl-mTLS/bin/*
docker cp svid-ng_assertingwl_1:/build/bin/. ./Assertingwl-mTLS/bin/
rm -f ./m-tier/bin/*
docker cp svid-ng_m-tier_1:/build/bin/. ./m-tier/bin/
rm -f ./subject_workload/bin/*
docker cp svid-ng_subjectwl_1:/build/bin/. ./subject_workload/bin/
rm -f ./target-wl/bin/*
docker cp svid-ng_target-wl_1:/build/bin/. ./target-wl/bin/

printf "${GREEN}Done! Containers up and running.${CLEAR}\n"