#!/bin/bash

#kill spire agent, spire server and containers
cd /opt/spire
sudo kill -9 $(ps -ef | grep "spire-agent" | grep -v grep | awk '{print $2}') ;  sudo kill -9 $(ps -ef | grep "spire-server" | grep -v grep | awk '{print $2}') ; sudo rm -rf .data
echo "Spire Agent/Server killed"

docker-compose down
echo "Containers killed"
