#!/bin/bash
# Initialize sample

set -e

SCRIPT_PATH=$(pwd)
GREEN='\033[0;32m'
CLEAR='\033[0m'

echo -e "${GREEN}Killing spire agent, spire server and containers...${CLEAR}\n"
./kill

echo -e "${GREEN}Starting SPIRE...${CLEAR}\n"
cd /opt/spire-signed-assertions
sudo bash start_spire_env.sh > /dev/null

echo -e "${GREEN}Applying ./.cfg ...${CLEAR}\n"
cd $SCRIPT_PATH
cp .cfg Assertingwl-mTLS
cp .cfg m-tier
cp .cfg m-tier2
cp .cfg m-tier3
cp .cfg m-tier4
cp .cfg m-tier5
cp .cfg subject_workload
cp .cfg target-wl

echo -e "${GREEN}Starting containers...${CLEAR}\n"
docker-compose up --build --detach

echo -e "${GREEN}Done! Containers up and running.${CLEAR}"