#!/bin/bash
# Initialize sample

set -e

SCRIPT_PATH=$(pwd)
GREEN='\033[0;32m'
CLEAR='\033[0m'

echo -e "${GREEN}Killing spire agent, spire server and containers...${CLEAR}\n"
./kill

echo -e "${GREEN}Starting SPIRE...${CLEAR}\n"
cd /opt/spire
sudo bash start_spire_env.sh > /dev/null

echo -e "${GREEN}Applying ./.cfg ...${CLEAR}\n"
cd $SCRIPT_PATH
cp .cfg Assertingwl-mTLS
cp .cfg m-tier
cp .cfg m-tier2
cp .cfg m-tier3
cp .cfg m-tier4
cp .cfg m-tier5
cp .cfg subject_workload
cp .cfg target-wl

echo -e "${GREEN}Starting containers...${CLEAR}\n"
docker-compose up --build --detach

echo -e "${GREEN}Copying WLs' binaries from containers to host..${CLEAR}\n"
rm -f ./Assertingwl-mTLS/bin/*
docker cp phase3_assertingwl_1:/build/bin/. ./Assertingwl-mTLS/bin/
rm -f ./subject_workload/bin/*
docker cp phase3_subjectwl_1:/build/bin/. ./subject_workload/bin/
rm -f ./m-tier/bin/*
docker cp phase3_m-tier_1:/build/bin/. ./m-tier/bin/
rm -f ./m-tier/bin/*
docker cp phase3_m-tier2_1:/build/bin/. ./m-tier2/bin/
rm -f ./m-tier/bin/*
docker cp phase3_m-tier3_1:/build/bin/. ./m-tier3/bin/
rm -f ./m-tier/bin/*
docker cp phase3_m-tier4_1:/build/bin/. ./m-tier4/bin/
rm -f ./m-tier/bin/*
docker cp phase3_m-tier5_1:/build/bin/. ./m-tier5/bin/
rm -f ./target-wl/bin/*
docker cp phase3_target-wl_1:/build/bin/. ./target-wl/bin/

echo -e "${GREEN}Done! Containers up and running.${CLEAR}\n"
